# Generated by Django 5.1.4 on 2025-05-13 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0005_alter_contact_email_alter_contact_first_name_and_more'),
        ('user_auth_app', '0003_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth_app.userprofile'),
        ),
    ]
